default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: openai_on_rails_development
  username: postgres

test:
  <<: *default
  database: openai_on_rails_test
  username: postgres

production:
  <<: *default
  database: openai_on_rails
  username: postgres
  password: iop342kj1ewfR!32
